##
## Copyright (c) 2022-2023 Geosiris.
## SPDX-License-Identifier: Apache-2.0
##

name: Generate 
Description: Generates code from avro-to-python-etp 

inputs:
  python-version:
    description: 'Python version to use'
    required: true
    default: '3.9'
  etp-file-name:
    description: 'etp avpr file name'
    required: true

runs:
  using: "composite"
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v3

    - name: Download ETP file
      run : wget http://geosiris.com/wp-content/uploads/2022/09/etp/${{ inputs.etp-file-name }} -P ${{ github.workspace }}

    - name: Install dependencies
        uses: ./.github/actions/prepare-poetry
        with:
          python-version: ${{ inputs.python-version }}

    - name: Translate avpr to avsc
      run: |
        poetry run avpr-to-avsc ${{ inputs.etp-file-name }}

    - name: Generate classes
      run: |
        poetry run avro-to-python-etp output/Energistics tmp --pip etptypes --package_version 0.0.0 --author "Valentin Gauthier <valentin.gauthier@geosiris.com>"

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: etptypes-generated-artifact-v${{ inputs.python-version }}
        retention-days: 1
        path: |
          ${{ github.workspace }}/tmp/etptypes/*