##
## Copyright (c) 2022-2023 Geosiris.
## SPDX-License-Identifier: Apache-2.0
##
---

name: Prepare Python and Poetry
Description: Install Python, Poetry and dev dependencies, cached for speed

inputs:
  python-version:  
    description: 'Python version to use'
    required: true
    default: '3.x'

  toml-path:
    description: 'path of the toml'
    required: false
    default: '.'


runs:
  using: "composite"
  steps:
    - name: Set up Python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Load cached Poetry installation
      uses: actions/cache@v4
      with:
        path: ~/.local  # the path depends on the OS
        key: poetry-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-0  # increment to reset cache

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 2.1.1
        virtualenvs-create: true
        virtualenvs-in-project: true
      
    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}-1
     
    - name: Install dependencies and library
      # if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: |
        cd ${{ inputs.toml-path }}
        poetry install --no-interaction
        poetry self add poetry-dynamic-versioning[plugin]
      shell: bash
  