##
## Copyright (c) 2022-2023 Geosiris.
## SPDX-License-Identifier: Apache-2.0
##
name: Tests

on:
  push:
  pull_request:

jobs:

  generate:
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    uses: .github/workflows/partials/build.yml
    with:
      python-version: ${{ matrix.python-version }}
    secrets: inherit

  unit-tests:
    needs: generate

    name: Unit tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: etptypes-generated-artifact-v${{ matrix.python-version }}
          path: etptypes/

      - name: Install dependencies
        uses: ./.github/actions/prepare-poetry
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pytest
        run: poetry run pytest --cov=etptypes --cov-report=xml --junitxml=pytest.xml
    
      - name: Upload pytest artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: Unit Test Results (Python ${{ matrix.python-version }})
          path: pytest.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
