name: Build-and-Push-TEST

on: [push,pull_request]

jobs:
  generate:
    name: Generate etptypes code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Download ETP file
        run : wget http://geosiris.com/wp-content/uploads/2022/09/etp/${{ secrets.ETP_FILE_NAME}} -P ${{ github.workspace }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning
          poetry install

      - name: Translate avpr to avsc
        run: |
          poetry run avpr-to-avsc ${{ secrets.ETP_FILE_NAME}}

      - name: Generate classes
        run: |
          poetry run avro-to-python-etp output/Energistics tmp --pip etptypes --package_version ${{ secrets.PACKAGE_VERSION }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: etptypes-generated-artifact
          retention-days: 1
          path: |
            ${{ github.workspace }}/tmp/etptypes/*
  
  build:
    needs: generate

    name: Building generated code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: etptypes-generated-artifact
          path: etptypes/

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning
          pip install black

      - name: Python Black
        run: |
          cd ${{ github.workspace }}/etptypes
          black -t py39 etptypes

      - name: Build Etptypes-python
        run: |
          cd etptypes
          poetry build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          retention-days: 1
          path: |
            ${{ github.workspace }}/etptypes/dist
            ${{ github.workspace }}/etptypes/pyproject.toml

  publish:
    needs: build

    name: Publish to PyPI-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-artifact
          path: etptypes/

      - name: Install Poetry
        run: |
          ls etptypes
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning

      - name: Upload to PyPI TEST
        run: |
          cd etptypes
          poetry config repositories.test https://test.pypi.org/legacy/
          poetry config http-basic.test ${{ secrets.POETRY_PYPI_TOKEN_USERNAME}} ${{ secrets.POETRY_TEST_PYPI_TOKEN_PASSWORD}}
          poetry publish --repository test