name: Build-and-Push

on:
  push:
    tags:
      # Run when a tag is pushed with a valid semantic version number
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  generate:
    name: Generate etptypes code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Download ETP file
        run : wget http://geosiris.com/wp-content/uploads/2022/09/etp/${{ secrets.ETP_FILE_NAME}} -P ${{ github.workspace }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pydantic typingx avro-to-python-etp

      - name: Translate avpr to avsc
        run: |
          avpr-to-avsc ${{ secrets.ETP_FILE_NAME}}

      - name: Generate classes
        run: |
          avro-to-python-etp output/Energistics tmp --pip etptypes --package_version ${{ secrets.PACKAGE_VERSION }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: etptypes-generated-artifact
          retention-days: 1
          path: |
            ${{ github.workspace }}/tmp/etptypes/*
  
  build:
    needs: generate

    name: Building generated code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: etptypes-generated-artifact
          path: etptypes/

      - name: Installation
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning
          pip install black

      - name: Python Black
        run: |
          cd ${{ github.workspace }}/etptypes
          black -t py39 etptypes

      - name: Build Etptypes-python
        run: |
          cd etptypes
          rm pyproject.toml
          cp ${{ github.workspace }}/pyproject.toml .
          cp ${{ github.workspace }}/LICENSE .
          cp ${{ github.workspace }}/README.md .
          poetry build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-artifact
          retention-days: 1
          path: |
            ${{ github.workspace }}/etptypes/dist
            ${{ github.workspace }}/etptypes/pyproject.toml
            ${{ github.workspace }}/etptypes/LICENSE
            ${{ github.workspace }}/etptypes/README.md

  publish:
    needs: build

    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-artifact
          path: etptypes/

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          pip install poetry-dynamic-versioning

      - name: Upload to PyPI
        run: |
          cd etptypes
          poetry publish --username ${{ secrets.POETRY_PYPI_TOKEN_USERNAME}} --password ${{ secrets.POETRY_PYPI_TOKEN_PASSWORD}}